on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
name: chart-releaser
jobs:
  helm-chart-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@users.noreply.github.com'
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      - name: Verify helm charts
        run: |
          cd $GITHUB_WORKSPACE
          helm lint ./charts/zot
          helm install --dry-run --generate-name --debug ./charts/zot
      - if: github.event_name == 'release' && github.event.action== 'published'
        name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
